apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      component : web
  template:
    metadata:
      labels:
        component: web
    spec: 
      containers:
        - name : client
          image: gurnoorsb/multi-client # this image have tag of latest = stephengrider/multi-client:latest automatically 
          ports:
           - containerPort: 3000
